# Site settings
title: opensvn的博客
url: "http://gitop.cc"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Shanghai
description: >
  大概就是一个乱七八糟的地方而已。

# Your information
# email: simon19860816@163.com
author: opensvn
avatar: "//www.gravatar.com/avatar/8e10df0bad4c56b3464cd715f8d96c46"
profile: 做自己喜欢的事
# twitter_username: laobubu
github_username: opensvn

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: opensvn  # get one: http://duoshuo.com/create-site/

permalink: /archives/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
